name: lattrans
channels:
  - pytorch
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - numpy=1.19.2
  - python=3.6.13
  - pip=21.1.1
  - pytorch=1.8.1
  - torchaudio=0.8.1
  - torchvision=0.9.1
  - pip:
    - face-alignment==1.3.4
    - opencv-python==4.5.2.52
    - scikit-image==0.17.2
    - scipy==1.2.0
    - pyyaml==5.4.1
    - tensorboard-logger==0.1.0
